/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as VendorsVendorIdRouteImport } from './routes/vendors.$vendorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: '/vendors/$vendorId',
  path: '/vendors/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/upload': typeof UploadRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/upload': typeof UploadRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/invoices': typeof InvoicesIndexRoute
  '/vendors': typeof VendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/upload': typeof UploadRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exceptions'
    | '/upload'
    | '/invoices/$invoiceId'
    | '/vendors/$vendorId'
    | '/invoices/'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exceptions'
    | '/upload'
    | '/invoices/$invoiceId'
    | '/vendors/$vendorId'
    | '/invoices'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/exceptions'
    | '/upload'
    | '/invoices/$invoiceId'
    | '/vendors/$vendorId'
    | '/invoices/'
    | '/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExceptionsRoute: typeof ExceptionsRoute
  UploadRoute: typeof UploadRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$vendorId': {
      id: '/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExceptionsRoute: ExceptionsRoute,
  UploadRoute: UploadRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  VendorsVendorIdRoute: VendorsVendorIdRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
